# CI_excise
hell
hello
hello
hello
hello
hello
hello
hello
hello
hello
.FFF.                                                                    [100%]
=================================== FAILURES ===================================
___________________________________ test_one ___________________________________

    def test_one():
>       assert main.verify_login("user",124321)
E       AssertionError: assert False
E        +  where False = <function verify_login at 0x7f863fdca440>('user', 124321)
E        +    where <function verify_login at 0x7f863fdca440> = main.verify_login

test_CI.py:7: AssertionError
___________________________________ test_two ___________________________________

    def test_two():
>       assert main.verify_login("משתמש",124321)
E       AssertionError: assert False
E        +  where False = <function verify_login at 0x7f863fdca440>('משתמש', 124321)
E        +    where <function verify_login at 0x7f863fdca440> = main.verify_login

test_CI.py:9: AssertionError
__________________________________ test_three __________________________________

    def test_three():
>       assert main.verify_login("user","123")
E       AssertionError: assert False
E        +  where False = <function verify_login at 0x7f863fdca440>('user', '123')
E        +    where <function verify_login at 0x7f863fdca440> = main.verify_login

test_CI.py:11: AssertionError
=========================== short test summary info ============================
FAILED test_CI.py::test_one - AssertionError: assert False
 +  where False = <function verify_login at 0x7f863fdca440>('user', 124321)
 +    where <function verify_login at 0x7f863fdca440> = main.verify_login
FAILED test_CI.py::test_two - AssertionError: assert False
 +  where False = <function verify_login at 0x7f863fdca440>('משתמש', 124321)
 +    where <function verify_login at 0x7f863fdca440> = main.verify_login
FAILED test_CI.py::test_three - AssertionError: assert False
 +  where False = <function verify_login at 0x7f863fdca440>('user', '123')
 +    where <function verify_login at 0x7f863fdca440> = main.verify_login
3 failed, 2 passed in 0.03s
\n\n___results from 2023-06-24____\n
.FFF.                                                                    [100%]
=================================== FAILURES ===================================
___________________________________ test_one ___________________________________

    def test_one():
>       assert main.verify_login("user",124321)
E       AssertionError: assert False
E        +  where False = <function verify_login at 0x7fbdaf8ea440>('user', 124321)
E        +    where <function verify_login at 0x7fbdaf8ea440> = main.verify_login

test_CI.py:7: AssertionError
___________________________________ test_two ___________________________________

    def test_two():
>       assert main.verify_login("משתמש",124321)
E       AssertionError: assert False
E        +  where False = <function verify_login at 0x7fbdaf8ea440>('משתמש', 124321)
E        +    where <function verify_login at 0x7fbdaf8ea440> = main.verify_login

test_CI.py:9: AssertionError
__________________________________ test_three __________________________________

    def test_three():
>       assert main.verify_login("user","123")
E       AssertionError: assert False
E        +  where False = <function verify_login at 0x7fbdaf8ea440>('user', '123')
E        +    where <function verify_login at 0x7fbdaf8ea440> = main.verify_login

test_CI.py:11: AssertionError
=========================== short test summary info ============================
FAILED test_CI.py::test_one - AssertionError: assert False
 +  where False = <function verify_login at 0x7fbdaf8ea440>('user', 124321)
 +    where <function verify_login at 0x7fbdaf8ea440> = main.verify_login
FAILED test_CI.py::test_two - AssertionError: assert False
 +  where False = <function verify_login at 0x7fbdaf8ea440>('משתמש', 124321)
 +    where <function verify_login at 0x7fbdaf8ea440> = main.verify_login
FAILED test_CI.py::test_three - AssertionError: assert False
 +  where False = <function verify_login at 0x7fbdaf8ea440>('user', '123')
 +    where <function verify_login at 0x7fbdaf8ea440> = main.verify_login
3 failed, 2 passed in 0.02s


___results from 2023-06-24____


.FFF.                                                                    [100%]
=================================== FAILURES ===================================
___________________________________ test_one ___________________________________

    def test_one():
>       assert main.verify_login("user",124321)
E       AssertionError: assert False
E        +  where False = <function verify_login at 0x7fd32c87e440>('user', 124321)
E        +    where <function verify_login at 0x7fd32c87e440> = main.verify_login

test_CI.py:7: AssertionError
___________________________________ test_two ___________________________________

    def test_two():
>       assert main.verify_login("משתמש",124321)
E       AssertionError: assert False
E        +  where False = <function verify_login at 0x7fd32c87e440>('משתמש', 124321)
E        +    where <function verify_login at 0x7fd32c87e440> = main.verify_login

test_CI.py:9: AssertionError
__________________________________ test_three __________________________________

    def test_three():
>       assert main.verify_login("user","123")
E       AssertionError: assert False
E        +  where False = <function verify_login at 0x7fd32c87e440>('user', '123')
E        +    where <function verify_login at 0x7fd32c87e440> = main.verify_login

test_CI.py:11: AssertionError
=========================== short test summary info ============================
FAILED test_CI.py::test_one - AssertionError: assert False
 +  where False = <function verify_login at 0x7fd32c87e440>('user', 124321)
 +    where <function verify_login at 0x7fd32c87e440> = main.verify_login
FAILED test_CI.py::test_two - AssertionError: assert False
 +  where False = <function verify_login at 0x7fd32c87e440>('משתמש', 124321)
 +    where <function verify_login at 0x7fd32c87e440> = main.verify_login
FAILED test_CI.py::test_three - AssertionError: assert False
 +  where False = <function verify_login at 0x7fd32c87e440>('user', '123')
 +    where <function verify_login at 0x7fd32c87e440> = main.verify_login
3 failed, 2 passed in 0.02s



__results from 2023-06-24__


.FFF.                                                                    [100%]
=================================== FAILURES ===================================
___________________________________ test_one ___________________________________

    def test_one():
>       assert main.verify_login("user",124321)
E       AssertionError: assert False
E        +  where False = <function verify_login at 0x7fe4158ba440>('user', 124321)
E        +    where <function verify_login at 0x7fe4158ba440> = main.verify_login

test_CI.py:7: AssertionError
___________________________________ test_two ___________________________________

    def test_two():
>       assert main.verify_login("משתמש",124321)
E       AssertionError: assert False
E        +  where False = <function verify_login at 0x7fe4158ba440>('משתמש', 124321)
E        +    where <function verify_login at 0x7fe4158ba440> = main.verify_login

test_CI.py:9: AssertionError
__________________________________ test_three __________________________________

    def test_three():
>       assert main.verify_login("user","123")
E       AssertionError: assert False
E        +  where False = <function verify_login at 0x7fe4158ba440>('user', '123')
E        +    where <function verify_login at 0x7fe4158ba440> = main.verify_login

test_CI.py:11: AssertionError
=========================== short test summary info ============================
FAILED test_CI.py::test_one - AssertionError: assert False
 +  where False = <function verify_login at 0x7fe4158ba440>('user', 124321)
 +    where <function verify_login at 0x7fe4158ba440> = main.verify_login
FAILED test_CI.py::test_two - AssertionError: assert False
 +  where False = <function verify_login at 0x7fe4158ba440>('משתמש', 124321)
 +    where <function verify_login at 0x7fe4158ba440> = main.verify_login
FAILED test_CI.py::test_three - AssertionError: assert False
 +  where False = <function verify_login at 0x7fe4158ba440>('user', '123')
 +    where <function verify_login at 0x7fe4158ba440> = main.verify_login
3 failed, 2 passed in 0.04s






__results from 2023-06-24__






.FFF.                                                                    [100%]
=================================== FAILURES ===================================
___________________________________ test_one ___________________________________

    def test_one():
>       assert main.verify_login("user",124321)
E       AssertionError: assert False
E        +  where False = <function verify_login at 0x7f728cb5a440>('user', 124321)
E        +    where <function verify_login at 0x7f728cb5a440> = main.verify_login

test_CI.py:7: AssertionError
___________________________________ test_two ___________________________________

    def test_two():
>       assert main.verify_login("משתמש",124321)
E       AssertionError: assert False
E        +  where False = <function verify_login at 0x7f728cb5a440>('משתמש', 124321)
E        +    where <function verify_login at 0x7f728cb5a440> = main.verify_login

test_CI.py:9: AssertionError
__________________________________ test_three __________________________________

    def test_three():
>       assert main.verify_login("user","123")
E       AssertionError: assert False
E        +  where False = <function verify_login at 0x7f728cb5a440>('user', '123')
E        +    where <function verify_login at 0x7f728cb5a440> = main.verify_login

test_CI.py:11: AssertionError
=========================== short test summary info ============================
FAILED test_CI.py::test_one - AssertionError: assert False
 +  where False = <function verify_login at 0x7f728cb5a440>('user', 124321)
 +    where <function verify_login at 0x7f728cb5a440> = main.verify_login
FAILED test_CI.py::test_two - AssertionError: assert False
 +  where False = <function verify_login at 0x7f728cb5a440>('משתמש', 124321)
 +    where <function verify_login at 0x7f728cb5a440> = main.verify_login
FAILED test_CI.py::test_three - AssertionError: assert False
 +  where False = <function verify_login at 0x7f728cb5a440>('user', '123')
 +    where <function verify_login at 0x7f728cb5a440> = main.verify_login
3 failed, 2 passed in 0.02s

__results from 2023-06-24__

.FFF.                                                                    [100%]
=================================== FAILURES ===================================
___________________________________ test_one ___________________________________

    def test_one():
>       assert main.verify_login("user",124321)
E       AssertionError: assert False
E        +  where False = <function verify_login at 0x7ffb8d1e6440>('user', 124321)
E        +    where <function verify_login at 0x7ffb8d1e6440> = main.verify_login

test_CI.py:7: AssertionError
___________________________________ test_two ___________________________________

    def test_two():
>       assert main.verify_login("משתמש",124321)
E       AssertionError: assert False
E        +  where False = <function verify_login at 0x7ffb8d1e6440>('משתמש', 124321)
E        +    where <function verify_login at 0x7ffb8d1e6440> = main.verify_login

test_CI.py:9: AssertionError
__________________________________ test_three __________________________________

    def test_three():
>       assert main.verify_login("user","123")
E       AssertionError: assert False
E        +  where False = <function verify_login at 0x7ffb8d1e6440>('user', '123')
E        +    where <function verify_login at 0x7ffb8d1e6440> = main.verify_login

test_CI.py:11: AssertionError
=========================== short test summary info ============================
FAILED test_CI.py::test_one - AssertionError: assert False
 +  where False = <function verify_login at 0x7ffb8d1e6440>('user', 124321)
 +    where <function verify_login at 0x7ffb8d1e6440> = main.verify_login
FAILED test_CI.py::test_two - AssertionError: assert False
 +  where False = <function verify_login at 0x7ffb8d1e6440>('משתמש', 124321)
 +    where <function verify_login at 0x7ffb8d1e6440> = main.verify_login
FAILED test_CI.py::test_three - AssertionError: assert False
 +  where False = <function verify_login at 0x7ffb8d1e6440>('user', '123')
 +    where <function verify_login at 0x7ffb8d1e6440> = main.verify_login
3 failed, 2 passed in 0.02s
